name: Install dependencies

inputs:
  qt-version:
    required: true
    default: '6.8.3'

runs: 
  using: "composite"
  steps:
    - name: Install CMake
      shell: bash
      run: sudo apt-get update -y && sudo apt-get install -y cmake

    - name: Install Ninja
      shell: bash
      run: sudo apt-get install -y ninja-build

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt-version }} 
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtshadertools'
    
    - name: Install OpenAL
      shell: bash
      run: sudo apt-get install -y libopenal-dev

    - name: Install GTest
      shell: bash
      run: sudo apt-get install -y libgtest-dev

    - name: Install gcovr
      shell: bash
      run: sudo apt-get install -y gcovr

    - name: Install xvbf
      shell: bash
      run: sudo apt-get install -y xvfb libxcb-cursor0

    - name: Install AnyRPC
      shell: bash
      run: |
        git clone https://github.com/sgieseking/anyrpc.git
        cd anyrpc
        mkdir build
        cd build
        cmake -DBUILD_EXAMPLES=OFF -DBUILD_WITH_LOG4CPLUS=OFF -DBUILD_PROTOCOL_MESSAGEPACK=OFF ..
        cmake --build .
        sudo cmake --install .

    - name: Install Spix
      shell: bash
      run: |
        git clone https://github.com/faaxm/spix
        cd spix
        mkdir build && cd build
        cmake -DSPIX_QT_MAJOR=6 -SPIX_BUILD_EXAMPLES=OFF ..
        cmake --build .
        sudo cmake --install .